from enum import Enum


class CommunicationProtocolIDs(Enum):

    GETSETDEVICESN = 0
    GETSETDEVICENAME = 1
    GETPOSE = 10
    RESETPOSE = 11
    GETALARMSSTATE = 20
    CLEARALLALARMSSTATE = 21
    SETGETHOMEPARAMS = 30
    SETHOMECMD = 31
    SETGETHHTTRIGMODE = 40
    SETGETHHTTRIGOUTPUTENABLED = 41
    GETHHTTRIGOUTPUT = 42
    SETGETARMORIENTATION = 50
    SETGETENDEFFECTORPARAMS = 60
    SETGETENDEFFECTORLAZER = 61
    SETGETENDEFFECTORSUCTIONCUP = 62
    SETGETENDEFFECTORGRIPPER = 63
    SETGETJOGJOINTPARAMS = 70
    SETGETJOGCOORDINATEPARAMS = 71
    SETGETJOGCOMMONPARAMS = 72
    SETGETPTPJOINTPARAMS = 80
    SETGETPTPCOORDINATEPARAMS = 81
    SETGETPTPJUMPPARAMS = 82
    SETGETPTPCOMMONPARAMS = 83
    SETPTPCMD = 84
    SETCPCMD = 91
    SETQUEUEDCMDSTARTEXEC = 240
    SETQUEUEDCMDSTOPEXEC = 241
    SETQUEUEDCMDCLEAR = 245
    GETQUEUEDCMDCURRENTINDEX = 246
